# Site configuration. Note that indentation matters to YAML - don't change the
# indentation of existing values! If you extend the file, you can of course
# supply whatever data you like. Note that PyYAML currently only supports the
# YAML 1.1 standard, not YAML 1.2.

site:
  name: Step Stool Demo
  root: http://step-stool.io/demo
  content:
    source: /Users/chris/development/personal_projects/step_stool/sample/source
    destination: /Users/chris/development/personal_projects/step_stool/sample/generated-site
  template:
    directory: /Users/chris/development/personal_projects/step_stool/sample/templates
    default: clean
  render_options:
    use_categories: true
    use_tags: true
    posts_per_page: 5 # used on archive, categories, and tags pages
    home:
      blog: true
      slug: # ignored if `blog` is `true`

publication:
  remote:
    push: true
    push_method: # must be one of ssh, sftp, or ftp-ssl

  git:
    push: false
    repository: # ignored if push = false
    push_method: # must be one of local, ssh, or https
    https_username: # only required if pushing via https - NOT RECOMMENDED
    https_password: # only required if pushing via https - NOT RECOMMENDED

  hg:
    push: false
    repository: # ignored if push = false
    push_method: # must be either local, ssh, or https
    https_username: # only required if pushing via https - NOT RECOMMENDED
    https_password: # only required if pushing via https - NOT RECOMMENDED

# Detailed configuration
archives:
  generate: true
  categories: true
  tags: true
  author: false

markdown_extensions: # See http://pythonhosted.org/Markdown/extensions/index.html for a list of extensions
  codehilite: # depends on Pygments (installed by default with
  extra: # includes a number of modules corresponding to the PHP Extra Markdown syntax
  headerid: # adds an ID attribute to header elements in HTML
  meta: # returns metadata from the top of Markdown files (like in MultiMarkdown)
  smartypants: # Smartypants typography
