# Basic site configuration
site-name: Step Stool Demo
root: http://step-stool.io/demo
content-source: /Users/chris/development/personal_projects/step-stool/sample/source
content-output: /Users/chris/development/personal_projects/step-stool/sample/generated-site
default-template: clean

# Publication configuration
remote:
  - push: true

github:
  - push: false
  - repository:

bitbucket:
  - push: false
  - repository:

# Detailed configuration
archives:
  - generate: true
  - categories: true
  - tags: true
  - author: false
