site-name: Step Stool Demo
root: http://step-stool.io/demo
content-source: /Users/chris/development/personal_projects/step-stool/sample/source
content-output: /Users/chris/development/personal_projects/step-stool/sample/generated-site
default-template: clean
