# Site configuration. Note that indentation matters to YAML - don't change the
# indentation of existing values! If you extend the file, you can of course
# supply whatever data you like. Note that PyYAML currently only supports the
# YAML 1.1 standard, not YAML 1.2.
#
# If you corrupt the existing version of a file, you can always generate a new
# one in the default state by running `step-stool --copy_defaults <filename>

site:
  name: Step Stool Demo
  root: http://step-stool.io/demo
  content:
    source: /Users/chris/development/personal_projects/step_stool/sample/source
    destination: /Users/chris/development/personal_projects/step_stool/sample/generated-site
  template:
    directory: /Users/chris/development/personal_projects/step_stool/sample/templates/clean
    default: base.html
    copy_elements:
      - css
  options:
    posts_per_page: 5 # used on archive, categories, and tags pages
    blog:
      use: true
      slug: # defaults to 'blog'
      template: # if left blank, the template.default option will be used
    categories:
      use: true
      slug: # defaults to 'categories'
      restrict: # if left blank and with no children, categories can be named arbitrarily
        - History
      template: # if left blank, the template.default option will be used
    tags:
      use: true
      slug: # defaults to 'tags'
      template: # if left blank, the template.default option will be used
    home:
      use: # use a standalone home page, rather than a list of the latest blog posts(s)
      source_slug: # the slug (with no extension) from which to generate the index page. See documentation!
      template: # if blank the template.default will be used; a page-specified template overrides this

publication:
  remote:
    push: true
    push_method: ssh # must be one of ssh, sftp, or ftp-ssl

  git:
    push: false
    repository: # ignored if push = false
    push_method: # must be one of local, ssh, or https
    https_username: # only required if pushing via https - NOT RECOMMENDED
    https_password: # only required if pushing via https - NOT RECOMMENDED

  hg:
    push: false
    repository: # ignored if push = false
    push_method: # must be either local, ssh, or https
    https_username: # only required if pushing via https - NOT RECOMMENDED
    https_password: # only required if pushing via https - NOT RECOMMENDED

markdown_extensions: # See http://pythonhosted.org/Markdown/extensions/index.html for a list of extensions
  - codehilite # depends on Pygments (installed by default with Python Markdown)
  - extra # includes a number of modules corresponding to the PHP Extra Markdown syntax
  - headerid # adds an ID attribute to header elements in HTML
  - meta # returns metadata from the top of Markdown files (like in MultiMarkdown)
  - smartypants # Smartypants typography
