# Basic site configuration
site_name: Step Stool Demo
root: http://step-stool.io/demo
content_source: /Users/chris/development/personal_projects/step-stool/sample/source
content_output: /Users/chris/development/personal_projects/step-stool/sample/generated-site
default_template: clean

# Publication configuration
remote:
  - push: true

github:
  - push: false
  - repository:
  - ssh_or_https: ssh
  - https_username:
  - https_password:

bitbucket:
  - push: false
  - repository:
  - ssh_or_https: ssh
  - https_username:
  - https_password:

# Detailed configuration
archives:
  - generate: true
  - categories: true
  - tags: true
  - author: false
